# Generated by Django 5.2.6 on 2025-09-29 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UchebniyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('number', models.IntegerField()),
                ('number_2', models.IntegerField()),
                ('u_plan', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=200)),
                ('cafedra', models.CharField(max_length=200)),
                ('kurs_semestr', models.CharField(max_length=200)),
                ('gruppa', models.CharField(max_length=200)),
                ('students_count', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('vid_zanatiy', models.CharField(max_length=200)),
                ('chasov', models.IntegerField()),
                ('vid_control', models.CharField(max_length=200)),
                ('individ_zanyatya', models.IntegerField()),
                ('nagruz_auditor', models.IntegerField()),
                ('nagruz_inoe', models.IntegerField()),
                ('nagruz_itogo', models.IntegerField()),
                ('n_potok', models.IntegerField()),
                ('id_first_group_potok', models.IntegerField()),
                ('description', models.TextField()),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['idd'],
                'indexes': [models.Index(fields=['disciplina'], name='raspred_uch_discipl_c1e8a1_idx')],
            },
        ),
    ]
