# Generated by Django 5.2.6 on 2025-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchebniyplan',
            name='nagruz_inoe_char',
            field=models.CharField(default='', max_length=200),
        ),
    ]
