# Generated by Django 5.2.6 on 2025-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspred', '0002_uchebniyplan_nagruz_inoe_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uchebniyplan',
            name='chasov',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='id_first_group_potok',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='idd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='individ_zanyatya',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='n_potok',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='nagruz_auditor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='nagruz_inoe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='nagruz_itogo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='number_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='students_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uchebniyplan',
            name='weeks',
            field=models.IntegerField(null=True),
        ),
    ]
